# Number of days of inactivity before an issue becomes stale
daysUntilStale: 150
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 300
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
# Label to use when marking an issue as stale
staleLabel: inactive
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: false
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed automatically. Please see https://github.com/Neamar/KISS/issues/1688 for details.
  Thank you for your contributions.
